// web/vue/Counter.vue
<template>
    <div>
        <button @click="increment">+1</button>
        <button v-on:click="reset">reset</button>
        <span>{{ count }}</span>
    </div>
</template>

<script>
export default {
    data() { return { count: 0 }; },
    methods: {
        increment() { this.count++; },
        reset() { this.count = 0; },
    }
};
</script>

// web/angular/counter.component.ts
import { Component } from '@angular/core';
@Component({ selector: 'app-counter', templateUrl: './counter.component.html' })
export class CounterComponent {
    count = 0;
    increment() { this.count++; }
    reset() { this.count = 0; }
}

<div>
    <button (click)="increment()">+1</button>
    <button (click)="reset()">reset</button>
    <span>{{ count }}</span>
</div>
