// web/react/Counter.tsx
import React, { useState } from 'react';

export function Counter() {
    const [count, setCount] = useState(0);
    function handleIncrement() { setCount(count + 1); }
    function handleReset() { setCount(0); }
    return (
        <div>
            <button onClick={handleIncrement}>+1</button>
            <button onClick={handleReset}>reset</button>
            <span>{count}</span>
        </div>
    );
}

export function App() {
    return <Counter />;
}

// web/angular/counter.component.ts
import { Component } from '@angular/core';
@Component({ selector: 'app-counter', templateUrl: './counter.component.html' })
export class CounterComponent {
    count = 0;
    increment() { this.count++; }
    reset() { this.count = 0; }
}

<div>
    <button (click)="increment()">+1</button>
    <button (click)="reset()">reset</button>
    <span>{{ count }}</span>
</div>
